FROM eclipse-temurin:11-jdk
WORKDIR /usr/local/lib
RUN apt-get update && \
    apt-get install -y curl && \
    curl -O https://www.antlr.org/download/antlr-4.13.1-complete.jar && \
    apt-get remove -y curl && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV CLASSPATH=".:/usr/local/lib/antlr-4.13.1-complete.jar:$CLASSPATH"
WORKDIR /app